// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookmarks.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (id, created_at, updated_at, user_id, post_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, post_id
`

type CreateBookmarkParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, createBookmark,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.PostID,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks
WHERE user_id = $1 AND post_id = $2
`

type DeleteBookmarkParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.UserID, arg.PostID)
	return err
}

const getUserBookmarks = `-- name: GetUserBookmarks :many
SELECT p.id, p.created_at, p.updated_at, p.title, p.url, p.description, p.published_at,
       f.name as feed_name, b.created_at as bookmarked_at
FROM bookmarks b
JOIN posts p ON b.post_id = p.id
JOIN feeds f ON p.feed_id = f.id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserBookmarksParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type GetUserBookmarksRow struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Title        string
	Url          string
	Description  sql.NullString
	PublishedAt  sql.NullTime
	FeedName     string
	BookmarkedAt time.Time
}

func (q *Queries) GetUserBookmarks(ctx context.Context, arg GetUserBookmarksParams) ([]GetUserBookmarksRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserBookmarks, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBookmarksRow
	for rows.Next() {
		var i GetUserBookmarksRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedName,
			&i.BookmarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isPostBookmarked = `-- name: IsPostBookmarked :one
SELECT EXISTS(
    SELECT 1 FROM bookmarks
    WHERE user_id = $1 AND post_id = $2
) as is_bookmarked
`

type IsPostBookmarkedParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) IsPostBookmarked(ctx context.Context, arg IsPostBookmarkedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isPostBookmarked, arg.UserID, arg.PostID)
	var is_bookmarked bool
	err := row.Scan(&is_bookmarked)
	return is_bookmarked, err
}
