// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addFeedToGroup = `-- name: AddFeedToGroup :exec
INSERT INTO feed_groups (feed_id, group_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddFeedToGroupParams struct {
	FeedID  uuid.UUID `json:"feed_id"`
	GroupID uuid.UUID `json:"group_id"`
}

func (q *Queries) AddFeedToGroup(ctx context.Context, arg AddFeedToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addFeedToGroup, arg.FeedID, arg.GroupID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name) VALUES ($1) RETURNING id, created_at, updated_at, name
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT id, created_at, updated_at, name FROM groups ORDER BY name
`

func (q *Queries) GetAllGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsByGroup = `-- name: GetFeedsByGroup :many
SELECT f.id, f.created_at, f.updated_at, f.name, f.url, f.last_fetched_at FROM feeds f
JOIN feed_groups fg ON f.id = fg.feed_id
WHERE fg.group_id = $1
ORDER BY f.name
`

func (q *Queries) GetFeedsByGroup(ctx context.Context, groupID uuid.UUID) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, created_at, updated_at, name FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getGroupsByFeed = `-- name: GetGroupsByFeed :many
SELECT g.id, g.created_at, g.updated_at, g.name FROM groups g
JOIN feed_groups fg ON g.id = fg.group_id
WHERE fg.feed_id = $1
ORDER BY g.name
`

func (q *Queries) GetGroupsByFeed(ctx context.Context, feedID uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsByFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFeedFromGroup = `-- name: RemoveFeedFromGroup :exec
DELETE FROM feed_groups WHERE feed_id = $1 AND group_id = $2
`

type RemoveFeedFromGroupParams struct {
	FeedID  uuid.UUID `json:"feed_id"`
	GroupID uuid.UUID `json:"group_id"`
}

func (q *Queries) RemoveFeedFromGroup(ctx context.Context, arg RemoveFeedFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeFeedFromGroup, arg.FeedID, arg.GroupID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET name = $2, updated_at = NOW() WHERE id = $1 RETURNING id, created_at, updated_at, name
`

type UpdateGroupParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup, arg.ID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
