// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            uuid.UUID  `json:"id"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	Name          string     `json:"name"`
	Url           string     `json:"url"`
	LastFetchedAt *time.Time `json:"last_fetched_at"`
}

type FeedGroup struct {
	FeedID  uuid.UUID `json:"feed_id"`
	GroupID uuid.UUID `json:"group_id"`
}

type Group struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
}

type Post struct {
	ID           uuid.UUID  `json:"id"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	Title        string     `json:"title"`
	Url          string     `json:"url"`
	Description  *string    `json:"description"`
	PublishedAt  *time.Time `json:"published_at"`
	FeedID       uuid.UUID  `json:"feed_id"`
	IsRead       bool       `json:"is_read"`
	IsBookmarked bool       `json:"is_bookmarked"`
	ThumbnailUrl *string    `json:"thumbnail_url"`
}
